### PR TITLE
Ignore errors when requiring files for inspection

### LINKED ISSUE #213: [Bug] Loading all files in app()->path() will cause errors when dependencies aren't loaded
Consider the following code from this repo: https://github.com/algolia/scout-extended/blob/ea5cec58af8f726fe1f5848082c0a5f84ffbd3b8/src/Helpers/SearchableFinder.php#L97-L101

In practice, this will load all `*.php` files . in your `app/` directory.

We have some service providers (e.g. `app/Providers/TelescopeServiceProvider`) that only load when on local. These classes depend on `laravel/telescope` to be installed via composer. Because these packages are a `--dev` requirement, they won't be installed in production.

However, because this piece of code is trying to load all files, php needs to be able to resolve the dependencies these files depend on. In the case of my `app/Providers/TelescopeServiceProvider`, this fails because `laravel/telescope` isn't installed in production:

```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found  
```

I'm not sure what would be the best way to resolve this. Silence errors? Add a blacklist to ignore certain classes from being loaded?

### PR DESCRIPTION
**Pull request by georgeboot**
Fixes #213 

I think this is the best approach. I've also considered creating a `E_USER_NOTICE` but Laravel still catches that as a full error.

In my opinion, no errors should be thrown and the code should just ignore the non-imported classes.

Alternatively, there are 2 (perhaps slightly better) approaches:

1. Log a warning to the log file
2. Keep track of files not imported and send them back to the command, and log them as warnings to the command line.

That last one sounds nice but involves quite a bit of passing through the collection of files; not really clean.

### CODE REVIEW

File: src/Helpers/SearchableFinder.php [hunk 1]
```diff
@@ -97,7 +98,11 @@ private function getProjectClasses(): array
             $configFiles = Finder::create()->files()->name('*.php')->in($this->app->path());
 
             foreach ($configFiles->files() as $file) {
-                require_once $file;
+                try {
+                    require_once $file;
+                } catch (Error $e) {
+                    // The file could not be loaded due to an error. Continue.
```
Comment (nunomaduro) [inline src/Helpers/SearchableFinder.php]: Do we have access to the console here? Maybe use `$command->info`? What do you think?

Comment (georgeboot) [reply src/Helpers/SearchableFinder.php]: Unless we would export `$command` as a global in the command itself (we shouldn't), `$command` will not be available here.

It's also not in the service container.

Comment (georgeboot) [reply src/Helpers/SearchableFinder.php]: I would just ignore these cases. The only real reason to log it to the user, would be to prevent unexpected  behaviour (classes not being scanned).

A reference in the docs seems good enough to me.

Comment (nunomaduro) [reply src/Helpers/SearchableFinder.php]: You can access the command from here: https://github.com/algolia/scout-extended/blob/13bce7535928e7ec6e1b2c777c6c6cad675dea21/src/Helpers/SearchableFinder.php#L57.

Pass the command into the find method, and put it as private. The class is internal, so we can do those changes.

Comment (georgeboot) [reply src/Helpers/SearchableFinder.php]: Ah I completely missed that. Was in a bit of a rush, my apologies. Pushed a fix.

File: src/Helpers/SearchableFinder.php [hunk 2]
```diff
@@ -56,6 +61,8 @@ public function __construct($app)
      */
     public function fromCommand(Command $command): array
     {
+        $this->command = $command;
```
Comment (nunomaduro) [inline src/Helpers/SearchableFinder.php]: I rather not persist state on the instance between two functions. Can you pass the command on the `find` method? Also, do we have tests for this? If not, can you add?

Comment (georgeboot) [reply src/Helpers/SearchableFinder.php]: Cool, did that.

I initially tried adding a test, but I'm just too unfamiliar with the code base (how all the mocks work) to get that working properly.

Perhaps you can have a look? You should have access to the repo.

File: tests/Features/SearchableFinderTest.php [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+        $filePath = \base_path('app/UnresolvableClass.php');
+        \file_put_contents(
+            $filePath,
+            \file_get_contents(\base_path('app/UnresolvableClass.php.stub'))
+        );
+
+        $this->artisan('scout:sync')->expectsOutput("{$filePath} could not be inspected due to an error being thrown while loading it.");
+
+        // remove the file again
+        unlink($filePath);
```
Comment (nunomaduro) [inline tests/Features/SearchableFinderTest.php]: This should be on the tearDown.

Comment (georgeboot) [reply tests/Features/SearchableFinderTest.php]: Fixed!

**Comment by nunomaduro** [comment]
Thank you!

**Comment by nunomaduro** [comment]
@georgeboot Looks our solution do not work in php 7.1 and php 7.2: https://travis-ci.org/algolia/scout-extended/builds/623665991.

Can you take a look?

**Comment by ametad** [comment]
Might I suggest an approach we used, as we had a similar problem?

Outlined in this class: https://github.com/matchish/laravel-scout-elasticsearch/blob/3ac43a86b46aa507e81e7c448c12cccd6317fd40/src/Searchable/SearchableListFactory.php#L22

Spoiler: it parses php and not load it.
